CXXFLAGS = ${CXX_STANDARD_FLAGS} ${CXX_WARNING_FLAGS} ${SUBPROJECT_CXXFLAGS}

LD = ld
LDFLAGS = ${SUBPROJECT_LDFLAGS}

%.o: %.cpp
	@echo "$(notdir $(CURDIR)): C++ $@"
	$(QUIET) $(CXX) $(CXXFLAGS) -o $@ -c $<

$(PROGRAM): $(OBJS)
	@echo "$(notdir $(CURDIR)): MERGE $(PROGRAM)"
	$(QUIET) $(CXX) $(LDFLAGS) $^ -o $(PROGRAM)

clean:
	@echo "$(notdir $(CURDIR)): CLEAN"
	$(QUIET) rm -rf $(PROGRAM)
	$(QUIET) rm -rf *.exec *.o